Registration changed for Laravel 5.4
shiftonelabs/laravel-nomad pull request #5
Opened 2017-01-27 11:35 UTC by SebastianS90

closes #4 

As this is a breaking change, I suggest to release it as version `2.0` and putting a note to the readme that `^1.0` is for Laravel `< 5.4` and `^2.0` is for Laravel `>= 5.4`.

The tests still need to be updated.

2017-01-27 13:40 UTC, SebastianS90 commented
Not sure about the test problems. Travis [succeeded](https://travis-ci.org/shiftonelabs/laravel-nomad/jobs/195867459) for PHP 7 but fails for the other environments. The reason might be my change from phpunit `~4.0` to `~5.0`. I had to update the dependency because of [this error](https://travis-ci.org/shiftonelabs/laravel-nomad/jobs/195841399#L280):
```
PHP Fatal error:  Class 'PHPUnit\Framework\TestCase' not found in /home/travis/build/shiftonelabs/laravel-nomad/vendor/laravel/framework/src/Illuminate/Foundation/Testing/TestCase.php on line 12
```

2017-01-27 21:46 UTC, SebastianS90 commented
I got the tests working on travis. The `phpunit` command just uses what is installed in the test VM, and that might not be compatible with what is pulled in by composer. So I switched to `./vendor/bin/phpunit`, thus ensuring compatibility.
Furthermore, Laravel and the current phpunit version do not support php 5.5 any more, so I removed it from the travis file.

In case that you release this backwards incompatible change as version `2.0.0`, then you can just use #6 to document how to use the correct version.

2017-02-08 05:31 UTC, patrickcarlohickman requested changes
Changes to prevent new major version for L5.4 support.

2017-02-08 05:31 UTC, patrickcarlohickman commented on .travis.yml
> -  - 5.5
Keep support for 5.5.

2017-02-08 05:31 UTC, patrickcarlohickman commented on composer.json
> -        "phpunit/phpunit": "~4.0",
I believe the older version is required to keep support for L4.

2017-02-08 05:31 UTC, patrickcarlohickman commented on src/LaravelNomadServiceProvider.php
> +        });
Do a check on `method_exists(Connection::class, 'resolverFor')`. If the method exists, use this new registration method. If the method doesn't exist, keep the old bindings.

2017-02-08 05:31 UTC, patrickcarlohickman commented on tests/TestCase.php
> +use Illuminate\Database\Connectors\ConnectionFactory;
To be consistent with Laravel, I keep my `use` statements in ascending order of length. This needs to be moved down a couple lines.

2017-02-08 08:03 UTC, SebastianS90 commented
Closed in favor of #7

2017-02-08 08:03 UTC, closed without merging